### ISSUE TITLE
Facebook login sometimes defaults to Michael Gardner

### ISSUE THREAD

**Issue by Mingling94** [makinj/MeNext#43]
Self explanatory, see: https://menext.me/party.php?partyId=73

**Comment by TheoBr** [comment]
Whoa. Yeah good catch thank you for reporting it

**Comment by makinj** [comment]
Thank you so much for this help
That would be my fault
I just refactored the backend and accidentally created an issue that we didn't think to test for.
please bear with me while I fix it.

**Comment by TheoBr** [comment]
For a full refactor, this is the tiniest issue I could imagine. Curious to see what it was!

**Comment by makinj** [comment]
Everything should be back in working order now!
sorry for the delay but I wasn't near a computer for a bit
